DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS comments_table;

CREATE TABLE IF NOT EXISTS comments_table
(
comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
text_of_comment varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS posts
(
post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title varchar(100) NOT NULL,
text_of_comment varchar NOT NULL,
comment_id BIGINT REFERENCES comments_table(comment_id) ON DELETE CASCADE,
image_path varchar,
likes_count BIGINT NOT NULL,
tags varchar(100) NOT NULL,
tags_as_text varchar NOT NULL,
text_preview varchar NOT NULL,
text_parts varchar NOT NULL
);